### PR TITLE
Add new feature: lesson1

### PR DESCRIPTION
**Pull request by IbnuAlii**
Pull Request Template

# Description

_Describe your changes in detail_

## Related Issue

_Reference the related issue(s) here, if applicable. For example, "Fixes #123" or "Addresses #456"_

## Proposed Changes

_Please describe the changes you've made. Include details about the problem you are solving and the approach you took to address it_.

## Screenshots (if applicable)

_Add screenshots to help explain your changes_.

### CODE REVIEW

**Comment by duraanali** [comment]
Asc @IbnuAlii , waa ku mahadsantahay code-ka lakin ma shaqeynaayo maxaa yeelay waa inuu ka mid yahay project-ga. Waa inaa component u sameyso sida "Lessons" ama "SideBar" ay component u tahay. Hadaysan macquul kuu aheyn, code-ka si gooni ah iigu soo dir, anaa isku dayaayo inu dhex galiyo.

**Comment by IbnuAlii** [comment]
wcs @duraanali thanks caawinaad baan u baahanahay lakiin. xoogaa waan fahmi waayay

**Comment by duraanali** [comment]
> wcs @duraanali thanks caawinaad baan u baahanahay lakiin. xoogaa waan fahmi waayay

Dhib malaha, anaa code-gaa copy dhahaayo kadibna soo galinaayo insha allah

**Comment by duraanali** [comment]
Asc @IbnuAlii, code-kaada waxaan ku dhex lifaaqay mid aan hada ka shaqeynaayo marka pull request gaan waan xiri insha allah, mahadsanid.

**Pull request closed without merging**
