### PR TITLE
forget password page

### PR DESCRIPTION
**Pull request by Ashakour1**
Pull Request Template

# Description

_Describe your changes in detail_

## Related Issue

_Reference the related issue(s) here, if applicable. For example, "Fixes #123" or "Addresses #456"_

## Proposed Changes

_Please describe the changes you've made. Include details about the problem you are solving and the approach you took to address it_.

## Screenshots (if applicable)

_Add screenshots to help explain your changes_.

### CODE REVIEW

**Comment by mahamedmahad** [comment]
@Ashakour1, Can you change LessonsData.jsx to LessonsData.tsx

**Comment by Ashakour1** [comment]
@mahamedmahad It can change but it already i done so.

**Comment by mahamedmahad** [comment]
@Ashakour1 Good,  push the changes to this Pull request

**Comment by mahamedmahad** [comment]
@Ashakour1 you need help resolving the conflicts?

**Comment by duraanali** [comment]
Asc @Ashakour1 , Thanks for the changes, can you resolve the conflict then push?

**Comment by Ashakour1** [comment]
check now @mahamedmahad

**Comment by Ashakour1** [comment]
@mahamedmahad  except me

**Comment by mahamedmahad** [comment]
@Ashakour1  i meant Disord - username( mahamed. ).  what is your Discord username?

**Comment by duraanali** [comment]
Sorry bro @Ashakour1 , can you rebase or merge it again, it has a conflict. Thanks.

**Pull request closed without merging**
