### PR TITLE
refactor - Update components

### PR DESCRIPTION
**Pull request by mahamedmahad**

### CODE REVIEW

**Review by duraanali — CHANGES_REQUESTED** [review]
The login page UI seems broken.

How it looks like:
logojn

How it should look like:
askjdhkashd

**Comment by mahamedmahad** [comment]
fixed it now,  forgot to push the incoming changes when I was resolving the conflicts. Now it should work

**Comment by duraanali** [comment]
> Author

Thanks for the fix!

**Review by duraanali — APPROVED** [review]
Looks good, thanks for the refactor!

**Pull request merged**
