### PR TITLE
Feature/footer

### PR DESCRIPTION
**Pull request by 4hmedhabib**
Pull Request Template

# Description

_Describe your changes in detail_

## Related Issue

_Reference the related issue(s) here, if applicable. For example, "Fixes #123" or "Addresses #456"_

## Proposed Changes

_Please describe the changes you've made. Include details about the problem you are solving and the approach you took to address it_.

## Screenshots (if applicable)

image

### CODE REVIEW

**Comment by 4hmedhabib** [comment]
Wcs @duraanali Ok.

**Comment by 4hmedhabib** [comment]
Waxaynu kusii socon doonna Issue ka kale ee furan

**Comment by duraanali** [comment]
Tabs-ka ma yareen kartaa, saan ayuu computer-ka u egyahay! 
jkaskdjhjkahsdkjhaskdjhaskhdas

Responsive markaan ka dhigana isma dul saarno!
ahskjdhaskkjhres

**Comment by 4hmedhabib** [comment]
Ok Tabs Aan kusoo Base gareeyo responsive ahaan. Sidoo kalena aan soo yareeyo Sections ka iyo wixii kale een kusoo daro ayaan kusoo PUSH and PR kusoo samaynayaa insha allah

**Comment by 4hmedhabib** [comment]
updated the  Footer  responsive

**Comment by duraanali** [comment]
Sorry @4hmedhabib, can you solve the conflict one more time then I will merge it.

**Comment by 4hmedhabib** [comment]
> Sorry @4hmedhabib, can you solve the conflict one more time then I will merge it.

@duraanali Solved

**Comment by duraanali** [comment]
Asc @4hmedhabib , waxyar aa qaldamay, wuxuu leeyahay, intaadan soo dirin `npm run build` samee, error-kuu soo saaro xali. Hada wuxuu ka hadlaayaa AuthProvider, file-kaas waan badalay.

kjhkkkkk

**Comment by 4hmedhabib** [comment]
Ok

**Comment by 4hmedhabib** [comment]
I pull the main branch then re-push feature/footer

**Comment by duraanali** [comment]
> I pull the main branch then re-push feature/footer

Waa inaa main branch aa pull ku sameyso, kadib aad gashid branch-kaada, markaas aa "git merge origin/main" dhahdo si is badalka ku jiro main uu kuu soo galo. Markaas kadib a conflict xalini.

Hada errorka kor ku jiro wuxuu tusaayaa file aan jirin, "AuthProvider" ma jiro.

**Comment by 4hmedhabib** [comment]
image

I build the project to check errors when I merge the upstream (duraanali/luuqa/main) merged the feature/footer branch

**Pull request merged**
